### ISSUE TITLE
"FATAL: Caught exception: File size is not a multiple of recordSize"

### ISSUE THREAD

**Issue by Silarous** [cculianu/Fulcrum#155] opened 2023-02-14 15:33 UTC
Found my Fulcrum server was down today and reporting this error.  Restarting the service brings the same error.  Any idea what the issue may be?  

Feb 14 09:29:19 Bitcoin Fulcrum[20054]: [2023-02-14 09:29:19.555] Loading database ...
Feb 14 09:29:19 Bitcoin Fulcrum[20054]: [2023-02-14 09:29:19.708] DB memory: 2048.00 MiB
Feb 14 09:29:19 Bitcoin Fulcrum[20054]: [2023-02-14 09:29:19.708] Coin: BTC
Feb 14 09:29:19 Bitcoin Fulcrum[20054]: [2023-02-14 09:29:19.708] Chain: main
Feb 14 09:29:19 Bitcoin Fulcrum[20054]: [2023-02-14 09:29:19.708] FATAL: Caught exception: File size is not a multiple of recordSize
Feb 14 09:29:19 Bitcoin Fulcrum[20054]: [2023-02-14 09:29:19.708] Stopping Controller ...
Feb 14 09:29:19 Bitcoin Fulcrum[20054]: [2023-02-14 09:29:19.708] Closing storage ...
Feb 14 09:29:19 Bitcoin Fulcrum[20054]: [2023-02-14 09:29:19.728] Shutdown complete
Feb 14 09:29:19 Bitcoin systemd[1]: fulcrum.service: Main process exited, code=exited, status=1/FAILURE
Feb 14 09:29:19 Bitcoin systemd[1]: fulcrum.service: Failed with result 'exit-code'.

**Comment by smilzo05** [comment] 2023-03-09 21:26
hi, i have the same problem, did you find a solution?  Thank you

**Comment by EchterAgo** [comment] 2023-03-09 21:51
Usually caused by unclean shutdown, duplicate of #41. You will have to start over with sync. It is a good idea to take backups of your Fulcrum data directory to restore from if this happens.

**Closed by EchterAgo** 2023-03-09 21:51 UTC

**Comment by EchterAgo** [comment] 2023-03-09 21:53
FYI, it helped me to keep my DB on a filesystem that can do CoW reflinks, that way you can just `cp --reflink=all` the data directory anytime to quickly take a backup.
