### ISSUE TITLE
Phoenix lightning wallet won't connect to my Fulcrum Electrum server

### ISSUE THREAD

**Issue by hMsats** [cculianu/Fulcrum#91] opened 2021-10-18 21:45 UTC
First of all: Fulcrum is an amazing Electrum server! Very fast!

Just wanted to bring this issue to your attention: https://github.com/ACINQ/phoenix/issues/188.

**Comment by cculianu** [comment] 2021-10-18 23:30
Hey man thanks a lot for the compliment and the positive vibes.

Hmm -- I read your issue. Ok let me ask you a few questions

- What OS are you on?
- Did you compile Fulcrum yourself or did you download the static build from the releases page?
- How is/was your SSL cert generated?  Are the private key and the public cert both in PEM format? Fulcrum relies on Qt's own internal SSL capabilities which are not quite as compatible with all cert formats as Python is.
- When you run Fulcrum, it should print information about the certificate in the log before it really finishes starting up. Does it say anything in particular? Maybe paste that part of the log?  Also you can run with `-d` to get a debug log too.

Maybe we can get to the bottom of this!

**Comment by cculianu** [comment] 2021-10-19 00:45
Ok, thanks for the output. Sadly, everything looks ok. You generated it with LetsEncrypt, which is what I use too. Qt, Fulcrum, and OpenSSL all seem to be happy with your cert.

I am left to wonder if this is not some issue with Phoenix wallet in some way, because your peers also have no trouble connecting to you.  I presume Electrum works ok, right?

**Comment by hMsats** [comment] 2021-11-09 20:31
Phoenix wallet also doesn't connect to my Fulcrum server over Tor (while my desktop Electrum connects without problems). So it doesn't look like a certificate/SSL problem. I connected Phoenix wallet over tor with an ElectrumX server and that worked. I then tried to connect Phoenix to another Fulcrum Electrum server (that also works on my desktop Electrum) and that failed as well. So the conclusion is: Phoenix wallet connects to ElectrumX but not Fulcrum. Other clients (BlueWallet, Electrum desktop, Electrum smartphone) have no problem connecting to Fulcrum.

**Comment by hMsats** [comment] 2021-11-12 12:56
@cculianu I finally found the cause! Phoenix wallet received the following error message from Fulcrum: `Expected jsonrpc version 2.0`

As you of course know, it's this part in RPC.cpp which generates this message 

```
        if (QString ver; !v1 && (ver=ret.jsonRpcVersion()) != RPC::jsonRpcVersion) {// we ignore this key in v1
            if (!ver.isEmpty())
                throw InvalidError(QString("Expected jsonrpc version %1").arg(RPC::jsonRpcVersion));
            // It turns out Electron Cash doesn't even send this key, even though JSON 2.0 spec specifies it. We accept
            // requests without it if the key is missing entirely, and "fake" it so below code works (what follows is
            // code that was originally written assuming the key is there).
            ret.data[s_jsonrpc] = RPC::jsonRpcVersion;
        }

```

and which I boldly turned into a comment:

```
        //if (QString ver; !v1 && (ver=ret.jsonRpcVersion()) != RPC::jsonRpcVersion) {// we ignore this key in v1
        //    if (!ver.isEmpty())
        //        throw InvalidError(QString("Expected jsonrpc version %1").arg(RPC::jsonRpcVersion));
            // It turns out Electron Cash doesn't even send this key, even though JSON 2.0 spec specifies it. We accept
            // requests without it if the key is missing entirely, and "fake" it so below code works (what follows is
            // code that was originally written assuming the key is there).
        //   ret.data[s_jsonrpc] = RPC::jsonRpcVersion;
        //}
```
which Phoenix connects to Fulcrum and also all my other Fulcrum clients continued to function normally after this change.

I don't know how this issue should be solved in an intelligent way or if it has to be solved here at all or needs to be solved by the Phoenix developers?

Finally the flickering  "Connecting ..." is gone!

**Comment by cculianu** [comment] 2021-11-12 13:34
WOW! Nice find! Much respect for digging this deeply!  I must say, this means that the Phoenix wallet devs are not implementing JSON-RPC spec correctly. But then again, neither did Electrum or Electron-Cash.

I will review what Phoenix sends to the server and adapt the code accordingly.  THANK YOU for finding this fix!

I will probably do a new release soon with this resolved in some way... since like it or not -- Phoenix has lots of "old" versions out there and even if they patch a new version.. old ones still won't work.

Thanks again for digging and figuring it out!

**Comment by cculianu** [comment] 2021-11-12 13:42
@hMsats : Hmm. Phoenix is written in Kotlin which I have to expend significant mental energy reading.. since I never really use Kotlin.  Do you happen to know offhand what a JSON-RPC request *does* look like from Phoenix? I am curious what they are putting there in the request object exactly if it isn't the string "2.0".

**Comment by hMsats** [comment] 2021-11-12 13:46
Thanks for all the complements! I just couldn't figure out what was going on until I discovered that Phoenix wallet on android has an option to view the logs. After that it was easy actually. I had been reading on the Internet how to view App logs in android but that wasn't so easy.

**Comment by cculianu** [comment] 2021-11-12 13:48
> Thanks for all the complements! I just couldn't figure out what was going on until I discovered that Phoenix wallet on android has an option to view the logs. After that it was easy actually. I had been reading on the Internet how to view App logs in android but that wasn't so easy.

Is there any way you can find out from the logs precisely *what* the message Phoenix sends looks like?

If not, I may have to just remove that check entirely ... it's Fulcrum being unnecessarily strict here, which seems to not help anybody really.

**Comment by cculianu** [comment] 2021-11-12 13:49
Oh -- you can run Fulcrum with `-d -d` (double verbose) and it SHOULD spit out "trace" information to logs... like tons of it.  If you do that -- we can **see the messages** from Phoenix.  If you can isolate some of those requests out for me -- that **would help immensely** @hMsats !!

**Comment by hMsats** [comment] 2021-11-12 13:50
You can have a look at my log [here](https://Bitkoins.nl/phoenix.log).

**Comment by cculianu** [comment] 2021-11-12 14:04
> You can have a look at the Phoenix log [here](https://Bitkoins.nl/phoenix.log). Is that enough or do you need the -d -d output?

Thanks for the log -- sadly it doesn't contain the actual JSON-RPC messages themselves (it's a "higher level" log). It does contain that error message you saw from Fulcrum, which helped you debug this though, so that's good.

Could you run Fulcrum with `-d -d` and find a snippet that contains a client request from Phoenix and show me that?

**Comment by hMsats** [comment] 2021-11-12 14:20
The (136 MB) output with the -d -d option is [here](https://Bitkoins.nl/out.txt). I returned to the original Fulcrum code that Phoenix wouldn't connect to. I don't know how to find the Phoenix output but I think if you search for 192.168.178.1 (that's me because I'm connect via WiFi at home) you'll find what you need.

**Comment by cculianu** [comment] 2021-11-12 15:46
Woah. Yeah it's a big file. This is very helpful! Thank you!

**Comment by cculianu** [comment] 2021-11-12 15:49
Ok yeah I see it. They are sending `"jsonrpc": "1.0"`.. and Fulcrum doesn't like that since Fulcrum is being a spec-nazi. IIRC the spec said that it "MUST" be empty, or contain the string "2.0" and nothing else.  It probably should simply just be more tolerant there.

I will fix it!

**Comment by cculianu** [comment] 2021-11-17 20:41
Ok, I am working on this now. I think I'll just make Fulcrum very permissive. Note that the Phoenix devs are implementing json-rpc 2.0 (or 1.0) incorrectly.  See here: https://www.jsonrpc.org/specification#request_object  

> **jsonrpc** - A String specifying the version of the JSON-RPC protocol. MUST be exactly `"2.0"`.

And for the 1.0 spec, there is **no mention** of the `jsonrpc` key at all.  In fact they explicitly state "it has 3 properties" here: https://www.jsonrpc.org/specification_v1#a1.1Requestmethodinvocation

But yeah, I'll just fix it.  This looks like the kind of problem that doesn't need to be a problem.  That key is ignored anyway by everything. :P

**Closed** 2021-11-17 21:51 UTC
Labels: SSL, Requires Investigation

**Comment by cculianu** [comment] 2021-11-17 21:57
Ok, the fix commit https://github.com/cculianu/Fulcrum/commit/6af3bc862bd597e22836739b246f57e843bbee55 has been pushed to master.  @hMsats  -- would you mind rebuilding master and testing again with Phoenix to just make sure it works for you now?

**Comment by hMsats** [comment] 2021-11-17 22:37
Yes, it works! Thanks for all the code changes. More than I expected. I'll close the issue also in the Phoenix GitHub with a remark that it was solved via a workaround. Again, thanks a lot for building this awesome product!

**Comment by cculianu** [comment] 2021-11-17 23:33
Hey man you're welcome and I'm glad you enjoy using it.  It scratched a personal itch for me -- ElectrumX just wasn't as fast as I would like and I wanted to see if we could go faster in C++.. and then it snowballed into a full-featured software product from there.

Anyway I probably will just issue another release today / right now since you confirmed the fix is good.  This warrants a release.

Thanks again!
