### ISSUE TITLE
Error on batched request

### ISSUE THREAD

**Issue by craigraw** [cculianu/Fulcrum#99] opened 2022-01-24 12:42 UTC
Fulcrum 1.6.0 ((Release 0bf5ddf, I recompiled to latest master branch) is giving an error on being presented with a batched request. Here are the relevant log lines from Sparrow:
```
Send: [{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[1],"id":1},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[2],"id":2},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[3],"id":3},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[4],"id":4},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[5],"id":5},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[10],"id":10},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[25],"id":25},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[50],"id":50}]
Recv: [{"error":{"code":-32600,"message":"Invalid request"},"id":null,"jsonrpc":"2.0"}]
```

When Sparrow sends these requests non-batched, all works well:
```
Send: {"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[1],"id":4}
Recv: {"id":4,"jsonrpc":"2.0","result":5.074e-05}
Send: {"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[2],"id":5}
Recv: {"id":5,"jsonrpc":"2.0","result":5.074e-05}
Send: {"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[3],"id":6}
Recv: {"id":6,"jsonrpc":"2.0","result":5.074e-05}
Send: {"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[4],"id":7}
Recv: {"id":7,"jsonrpc":"2.0","result":3.004e-05}
Send: {"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[5],"id":8}
Recv: {"id":8,"jsonrpc":"2.0","result":3.004e-05}
Send: {"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[10],"id":9}
Recv: {"id":9,"jsonrpc":"2.0","result":1.381e-05}
Send: {"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[25],"id":10}
Recv: {"id":10,"jsonrpc":"2.0","result":1.019e-05}
```

The batched request does work in ElectrumX and Electrs.

**Comment by cculianu** [comment] 2022-01-24 15:51
Ugh. Yeah. bug.

**Comment by cculianu** [comment] 2022-01-24 15:59
Ok well the problem is a `null` as an `id` in a request. I didn't want to support that due to the ambiguity that may create between request errors and results.  

Now that I think about it the Fulcrum batched request implementation is limited due to Fulcrum's architecture. I may just disable it altogether.

Fulcrum just doesn't like batches and i would have to rework how it thinks about JSON-RPC requests and responses, by adding another layer of abstraction to really support `null` request ids.  The way I am doing it now is a bit of a hack.

If `null` request id's really are required by many apps, maybe I should just disable batches altogether then, for now.

**Comment by cculianu** [comment] 2022-01-24 16:01
Oh no wait I cannot reproduce the error. It works here.

**Comment by craigraw** [comment] 2022-01-24 17:02
I recompiled to make sure, but I'm still getting the same, even with netcat on the command line:

```shell
echo '[{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[1],"id":1},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[2],"id":2},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[3],"id":3},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[4],"id":4},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[5],"id":5},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[10],"id":10},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[25],"id":25},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[50],"id":50}]' | nc localhost 53001 -i 1
```

Is this command working on your side?

**Comment by cculianu** [comment] 2022-01-24 18:48
This is truly perplexing. I run the command (adjusted for my setup here, port `60001` since I'm on testnet):

```bash
calin@CalinMBP2019 ~/src/ec/Fulcrum/build $ echo '[{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[1],"id":1},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[2],"id":2},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[3],"id":3},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[4],"id":4},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[5],"id":5},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[10],"id":10},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[25],"id":25},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[50],"id":50}]' | nc localhost 60001 -i 1
[{"id":2,"jsonrpc":"2.0","result":1e-05},{"id":1,"jsonrpc":"2.0","result":1e-05},{"id":3,"jsonrpc":"2.0","result":1e-05},{"id":10,"jsonrpc":"2.0","result":1e-05},{"id":5,"jsonrpc":"2.0","result":1e-05},{"id":4,"jsonrpc":"2.0","result":1e-05},{"id":25,"jsonrpc":"2.0","result":1e-05},{"id":50,"jsonrpc":"2.0","result":1e-05}]
```

.. and it works perfectly. 

---

I am actually going to redo some of the internals of batching though -- there are some questionable limitations in Fulcrum right now which I think I have a solution for (I wrote you an earlier message in here about them, then deleted it).  

The limitations in Fulcrum are:

- each `id` in the batch must be unique (note: JSON-RPC spec doesn't have this limitation)
- `null` values for `id` in a batch are not supported (JSON-RPC spec does not have this restriction)
- 2 or more extant batches must have unique `id` values (again, this limitation doesn't exist in JSON-RPC spec, nor in ElectrumX, etc).

However none of these limitations should be hit with that specific request.. UNLESS you are also sending another batch in parallel that conflicts with that.

I'm truly perplexed here!!  From the commit hash in the Fulcrum version it should totally be using batches.  I'm on the same hash here!


The weirdness aside (which I do hope we can resolve) -- I **am** working on redoing the batching internals today anyway.  So now is a good time to also troubleshoot what's going on.  If you can run Fulcrum with `-d` (or even `-d -d` for TRACE output) and see if anything pops out at you in the log output for the request, that may elucidate what's going on.

**Comment by craigraw** [comment] 2022-01-24 19:57
I've just tried again, and now the netcat request works!? - so even more perplexing. It must be something to do with the way Sparrow is issuing requests. After opening the socket, Sparrow sends and receives the following serially (without closing the socket):
```
Send: {"jsonrpc":"2.0","method":"server.version","params":["Sparrow","1.4"],"id":1}
Recv: {"id":1,"jsonrpc":"2.0","result":["Fulcrum 1.6.0","1.4"]}
Send: {"jsonrpc":"2.0","method":"blockchain.headers.subscribe","params":[],"id":2}
Recv: {"id":2,"jsonrpc":"2.0","result":{"height":720221,"hex":"040040209503e8c6daabf7d61f9e653eea45516ea7a0b58f648409000000000000000000c81a94ce710f2c572df7f611c154f12357769b7a4a9e211d738451154a6d1db103f3ee6180900a1787a6899d"}}
Send: {"jsonrpc":"2.0","method":"server.banner","params":[],"id":3}
Recv: {"id":3,"jsonrpc":"2.0","result":"quadnode Fulcrum 1.6.0\n\n/Satoshi:0.21.1/\n"}
Send: [{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[1],"id":4},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[2],"id":5},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[3],"id":6},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[4],"id":7},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[5],"id":8},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[10],"id":9},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[25],"id":10},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[50],"id":11}]
Recv: [{"error":{"code":-32600,"message":"Invalid request"},"id":null,"jsonrpc":"2.0"}]
```

Here's Fulcrum's trace logging for the failed call:
```
Jan 24 19:37:11 quadnode Fulcrum[46833]: [2022-01-24 19:37:11.300] <TcpSrv 0.0.0.0:50001> (Trace) on_readyRead
Jan 24 19:37:11 quadnode Fulcrum[46833]: [2022-01-24 19:37:11.300] <TcpSrv 0.0.0.0:50001> (Trace) Got: [{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[1],"id":4},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[2],"id":5},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[3],"id":6},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[4],"id":7},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[5],"id":8},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[10],"id":9},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[25],"id":10},{"jsonrpc":"2.0","method":"blockchain.estimatefee","params":[50],"id":11}]
Jan 24 19:37:11 quadnode Fulcrum[46833]: [2022-01-24 19:37:11.301] <TcpSrv 0.0.0.0:50001> (Debug) onPeerError, client 3192 error: Invalid request
Jan 24 19:37:11 quadnode Fulcrum[46833]: [2022-01-24 19:37:11.301] <TcpSrv 0.0.0.0:50001> (Trace) Sending result json: [{"error":{"code":-32600,"message":"Invalid request"},"id":null,"jsonrpc":"2.0"}]
Jan 24 19:37:11 quadnode Fulcrum[46833]: [2022-01-24 19:37:11.301] <TcpSrv 0.0.0.0:50001> (Trace) on_bytesWritten
```

**Comment by cculianu** [comment] 2022-01-24 21:20
Ok this must be a bug on a lower level, and specific to ARM.  I am not currently synched on my Rpi though so I will ask you to try this in the meantime:

- I suspect it may be a bug in the `simdjson` backend used by Fulcrum.  Maybe you can try to run Fulcrum with `simdjson` disabled, either using `--no-simdjson` on the CLI or `simdjson=false` in the conf file.

Otherwise I am completely at a loss.

Note that I **am** in the process of completely revamping the logic in the batch processor to be less limited. However, from the looks of this problem, somehow Fulcrum thinks the client didn't really send it a JSON Array, when it really actually did. Which is perplexing and leads me to believe there may be a bug that is ARM-specific and related to the JSON parser.

Hmm.

**Comment by cculianu** [comment] 2022-01-24 21:22
Note that if I copy-paste the exact lines Sparrow sends in a telnet session or using `nc`, everything works here.

**Comment by cculianu** [comment] 2022-01-24 21:26
I may just install sparrow -- I never used it.  Got a link handy?

**Comment by cculianu** [comment] 2022-01-24 22:31
Hey I just pushed a commit to master that fixes some of the quirks of the batching implementation to Fulcrum. It's commit 911059ca9b5ece6edc727c00af2c3b8d3942d7fc.  I recommend you try it anyway, despite the fact that I am not exactly optimistic that it will fix the issue we see here.

**Comment by cculianu** [comment] 2022-01-25 03:37
Good news! I synched my RPI and indeed I am getting the exact same issue.  This is mysterious. Works perfectly on x86 on all 3 platforms: Linux, OSX, Windows (all x86).

It definitely is some strangeness. I am investigating...

**Comment by cculianu** [comment] 2022-01-25 04:26
Ok, this has been fixed on master.  It turns out there were compiler differences between clang (what I use) and GCC.  It was breaking on all GCC builds.  TODO (for me): Add some better CI tests to detect such things.

Fixed, closing.

**Closed by cculianu** 2022-01-25 04:26 UTC

**Comment by craigraw** [comment] 2022-01-25 05:03
Confirmed fixed! Thank you.

If you're still interested, it's easiest to get Sparrow from https://sparrowwallet.com/download

**Comment by cculianu** [comment] 2022-01-25 05:12
Awesome, thanks I'll install it tomorrow and test it out. I normally use BCH, and Electron Cash, which I maintain for BCH.  So.. hence my ignorance of the latest BTC wallets. :)

But yes, I do wish to test it out. Thanks!
